/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateItemArgs {
  'day' : bigint,
  'title' : string,
  'tripId' : bigint,
  'time' : string,
  'description' : string,
  'category' : string,
  'location' : string,
}
export interface CreateTripArgs {
  'title' : string,
  'destination' : string,
  'endDate' : string,
  'description' : string,
  'startDate' : string,
}
export interface ItineraryItem {
  'id' : bigint,
  'day' : bigint,
  'title' : string,
  'tripId' : bigint,
  'time' : string,
  'description' : string,
  'category' : string,
  'location' : string,
}
export interface Trip {
  'id' : bigint,
  'title' : string,
  'destination' : string,
  'endDate' : string,
  'ownerId' : Principal,
  'description' : string,
  'startDate' : string,
}
export interface UpdateTripArgs {
  'id' : bigint,
  'title' : [] | [string],
  'destination' : [] | [string],
  'endDate' : [] | [string],
  'description' : [] | [string],
  'startDate' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addItem' : ActorMethod<[CreateItemArgs], ItineraryItem>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTrip' : ActorMethod<[CreateTripArgs], Trip>,
  'deleteItem' : ActorMethod<[bigint], undefined>,
  'deleteTrip' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getItem' : ActorMethod<[bigint], [] | [ItineraryItem]>,
  'getItemsByTrip' : ActorMethod<[bigint], Array<ItineraryItem>>,
  'getTrip' : ActorMethod<[bigint], [] | [Trip]>,
  'getTripsByOwner' : ActorMethod<[Principal], Array<Trip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateItem' : ActorMethod<[CreateItemArgs, bigint], ItineraryItem>,
  'updateTrip' : ActorMethod<[UpdateTripArgs], Trip>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];