/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateItemArgs = IDL.Record({
  'day' : IDL.Nat,
  'title' : IDL.Text,
  'tripId' : IDL.Nat,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const ItineraryItem = IDL.Record({
  'id' : IDL.Nat,
  'day' : IDL.Nat,
  'title' : IDL.Text,
  'tripId' : IDL.Nat,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateTripArgs = IDL.Record({
  'title' : IDL.Text,
  'destination' : IDL.Text,
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Trip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'destination' : IDL.Text,
  'endDate' : IDL.Text,
  'ownerId' : IDL.Principal,
  'description' : IDL.Text,
  'startDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UpdateTripArgs = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Opt(IDL.Text),
  'destination' : IDL.Opt(IDL.Text),
  'endDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItem' : IDL.Func([CreateItemArgs], [ItineraryItem], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTrip' : IDL.Func([CreateTripArgs], [Trip], []),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'deleteTrip' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItem' : IDL.Func([IDL.Nat], [IDL.Opt(ItineraryItem)], ['query']),
  'getItemsByTrip' : IDL.Func([IDL.Nat], [IDL.Vec(ItineraryItem)], ['query']),
  'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
  'getTripsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateItem' : IDL.Func([CreateItemArgs, IDL.Nat], [ItineraryItem], []),
  'updateTrip' : IDL.Func([UpdateTripArgs], [Trip], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateItemArgs = IDL.Record({
    'day' : IDL.Nat,
    'title' : IDL.Text,
    'tripId' : IDL.Nat,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const ItineraryItem = IDL.Record({
    'id' : IDL.Nat,
    'day' : IDL.Nat,
    'title' : IDL.Text,
    'tripId' : IDL.Nat,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateTripArgs = IDL.Record({
    'title' : IDL.Text,
    'destination' : IDL.Text,
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Trip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'destination' : IDL.Text,
    'endDate' : IDL.Text,
    'ownerId' : IDL.Principal,
    'description' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UpdateTripArgs = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Opt(IDL.Text),
    'destination' : IDL.Opt(IDL.Text),
    'endDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItem' : IDL.Func([CreateItemArgs], [ItineraryItem], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTrip' : IDL.Func([CreateTripArgs], [Trip], []),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'deleteTrip' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItem' : IDL.Func([IDL.Nat], [IDL.Opt(ItineraryItem)], ['query']),
    'getItemsByTrip' : IDL.Func([IDL.Nat], [IDL.Vec(ItineraryItem)], ['query']),
    'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
    'getTripsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateItem' : IDL.Func([CreateItemArgs, IDL.Nat], [ItineraryItem], []),
    'updateTrip' : IDL.Func([UpdateTripArgs], [Trip], []),
  });
};

export const init = ({ IDL }) => { return []; };